name: Build with Packer

on:
  push:
    branches:
      - main

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  packer-build:
    name: Packer 📦 Build 🛠️
    environment: ${{ vars.ENVIRONMENT }}
    runs-on: [ Windows, "${{ vars.ENVIRONMENT }}" ]
    env:
        VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
        VAULT_ADDR: ${{ vars.VAULT_ADDR }}
        CONSUL_HTTP_ADDR: ${{ vars.CONSUL_HTTP_ADDR }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cleanup 🧹
        working-directory: infra/windows-ami
        run: |
          Remove-Item ".vagrant" -Recurse -Force -ErrorAction SilentlyContinue
          Remove-Item "packer_cache" -Recurse -Force -ErrorAction SilentlyContinue
          Remove-Item "output" -Recurse -Force -ErrorAction SilentlyContinue

      - name: Build 🛠️
        working-directory: infra/windows-ami
        run: |
          packer build -force main.pkr.hcl

      - name: Publish 📦
        shell: powershell
        env:
          BOX_NAME: "windows-server-2022"
          BOX_VERSION: "1.0.0"
          BOX_PROVIDER: "virtualbox"
          BOX_URL_BASE: "http://localhost:8040/vagrant/boxes/"
          REGISTRY_ROOT: "D:\boxes"
          BOX_FILE: "D:\workspace\ami\infra\\windows-ami\output\Windows Server 2022_64-vagrant.box"
        run: |
          .\scripts\box-metadata.ps1 -BoxFile ${{ env.BOX_FILE }} -BoxName ${{ env.BOX_NAME }} -BoxVersion ${{ env.BOX_VERSION }} -Provider ${{ env.BOX_PROVIDER }} -RegistryRoot ${{ env.REGISTRY_ROOT }} -BoxUrlBase ${{ env.BOX_URL_BASE }}