name: Build with Packer

on:
  push:
    branches:
      - main

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  packer-build:
    name: Packer 📦 Build 🛠️
    environment: ${{ vars.ENVIRONMENT }}
    runs-on: [ Windows, "${{ vars.ENVIRONMENT }}" ]
    env:
        VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
        VAULT_ADDR: ${{ vars.VAULT_ADDR }}
        CONSUL_HTTP_ADDR: ${{ vars.CONSUL_HTTP_ADDR }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.2.0
        with:
          versionSpec: '6.2.x'

      - name: Cleanup 🧹
        working-directory: infra/windows-ami
        run: |
          Remove-Item ".vagrant" -Recurse -Force -ErrorAction SilentlyContinue
          Remove-Item "packer_cache" -Recurse -Force -ErrorAction SilentlyContinue
          Remove-Item "output" -Recurse -Force -ErrorAction SilentlyContinue

      - name: Build 🛠️
        working-directory: infra/windows-ami
        run: |
          packer build -force main.pkr.hcl

      - name: Determine Version
        id: version_step # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v3.2.0

      - name: Publish 📦
        shell: powershell
        env:
          BOX_NAME: "windows-server-2022"
          BOX_VERSION: "${{ steps.version_step.outputs.semver }}"
          BOX_PROVIDER: "virtualbox"
          BOX_URL_BASE: "http://localhost:8040/vagrant/boxes/"
          REGISTRY_ROOT: "D:\\boxes"
          BOX_FILE: ".\\infra\\windows-ami\\output\\Windows_Server_2022_64-vagrant.box"
        run: |
          .\scripts\box-metadata.ps1 -BoxFile ${{ env.BOX_FILE }} -BoxName ${{ env.BOX_NAME }} -BoxVersion ${{ env.BOX_VERSION }} -Provider ${{ env.BOX_PROVIDER }} -RegistryRoot ${{ env.REGISTRY_ROOT }} -BoxUrlBase ${{ env.BOX_URL_BASE }}